parameters:
    aw.hal_rest.listener.class: Alterway\Bundle\RestHalBundle\EventListener\ResourceListener

services:
    aw.hal_rest.listener:
        class: %aw.hal_rest.listener.class%
        arguments: []
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }
